export const ADD_MOVIE = 'addMovie'
export const ADD_ONE_MOVIE = 'addOneMovie'
export const GET_MOVIES = 'getMovies'
export const FETCH_MOVIES = 'fetch_movies'
export const REMOVE_MOVIE = 'removeMovie'
export const DELETE_MOVIE = 'deleteMovie'